### ISSUE TITLE
Spelling Error in Source 1.2.2

### ISSUE THREAD

**Issue by romitrajsahu** [techlore/go-incognito#20]
![Screenshot_20210614_095832](https://user-images.githubusercontent.com/81353919/121839159-284c2780-ccf7-11eb-8750-af91ab870588.png)

Instead of 'Declaration', it is written 'Deceleration'.

Please fix this.

**Comment by techlore-official** [comment]
https://github.com/techlore/go-incognito/commit/e34cf08c595df85494dcbfb5cc5feda4b2c42e7c
Fixed!
