### ISSUE TITLE
Section 3.8 extremely out of date

### ISSUE THREAD

**Issue by fried-tantrum** [techlore/go-incognito#21]
At least for the free version. Not sure if this was fixed on the paid version.

-HTTPS Everywhere is no longer necessary as Firefox includes it natively (but it must be activated in the settings). (Also most places are transitioning to TLS over SSL. Not really a big deal, but if you're redoing it, may as well change your wording/graphic, too)
-Privacy Badger is also probably not necessary anymore since it no longer learns and instead draws on a list of trackers. I've been told uBlock has a much more comprehensive list. Unless you want users to enable the learning in the settings.
-Consider LocalCDN over Decentraleyes. LocalCDN gets updated much more frequently.
-Cookie Autodelete is also kind of redundant if you set Firefox to clear data on closure. CA does it faster, but it's still redundant.
-uMatrix is no longer supported and hasn't been for quite some time, should probably be removed altogether.

**Comment by techlore-official** [comment]
Thanks for the great notes! Just updated the changelog to reference your updates:
https://github.com/techlore/go-incognito/commit/6bf4e1f4ed70721d3343555f55f36bd72afff95a#diff-0541a2b7e298ac99ae17f17d35f0e8435e2b998bbefcb7a3cf6db8b511746db9
