### ISSUE TITLE
Footer Updates

### ISSUE THREAD

**Issue by henry-fisher** [techlore/go-incognito#45]
<img width="307" alt="image" src="https://github.com/techlore/go-incognito/assets/64515030/28d7e1c9-0aea-443f-a1f7-206caaec9545">

* Replace contact@techlore.tech --> URL to our contact page: https://techlore.tech/contact (Can just say "Contact Us" as the link preview)
* If possible, let's add Mastodon to socials
* If possible, let's add our forum down here too
* Add coaching if possible
* Anything else you feel is good to add @jonaharagon 
* Copyright 2024

**Comment by jonaharagon** [comment]
![2024-08-07 at 10 22 26](https://github.com/user-attachments/assets/10533d73-405a-4f2a-948a-c199f65d8c56)
